---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juniolima-serverless-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juniolima-serverless-redis
  template:
    metadata:
      labels:
        app: juniolima-serverless-redis
    spec:
      containers:
      - name: juniolima-serverless-redis
        image: junioveras/serverless-runtime:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: pyfile
          mountPath: "/opt/usermodule.py"
          subPath: pyfile
        - name: zipfile
          mountPath: "/opt/user_function.zip"
          subPath: zipfile
        env:
        - name: REDIS_HOST
          value: "192.168.121.48"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: config
              key: REDIS_INPUT_KEY
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
        - name: MONITORING_PERIOD
          valueFrom:
            configMapKeyRef:
              name: config
              key: MONITORING_PERIOD
        - name: PYFILE_OR_ZIP
          value: "zip"
        - name: ZIP_FILE_PATH
          value: "/opt/user_function.zip"
        - name: ZIP_ENTRY_FILE
          value: "handler.py"
        - name: PYFILE_PATH
          value: "/opt/usermodule.py"
        - name: ENTRY_FUNCTION
          valueFrom:
            configMapKeyRef:
              name: config
              key: ENTRY_FUNCTION
      volumes:
      - name: pyfile
        configMap:
          name: pyfile
      - name: zipfile
        configMap:
          name: zipfile

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  REDIS_INPUT_KEY: "metrics"
  MONITORING_PERIOD: "5"
  ENTRY_FUNCTION: "handler"
  REDIS_OUTPUT_KEY: "juniolima-proj3-output"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zipfile
data:
  zipfile: |
    UEsDBBQAAAAIACSInVnC9tWwzgEAAHMFAAAHABwAbWFpbi5weVVUCQADhKpxZ5yucWd1eAsAAQTo
    AwAABOgDAACNU8uOozAQvOcrLE6QCRn2ModIOz+CkOWYJniH2MhuMpuN8u/bGDaYPDbhhLtc1VWt
    dgkVq4UuG7Cx0m2HG1YqiSsmjUb4TUez/QUSE5Z+eiR3aFesaozAYrNg9G2PCI470Mh+Mq+RRxqQ
    K8Ol6UjFOg5YZ+l0MSoCpgV5eInZXxyZqgrbvoVKnywbfPVfC1bSDU6q38Z+cdhZcI66xQH9fXYK
    xZKELdmPLPN60Dh4QTlbZwt/aw97Y49cCllDOQU8KIudaPgApwM8xhop266qKPtDzojPSWhQNA8p
    Hp2GN+PcnVjovp9XPI/zduU1oSmGos8Hd9XgMjbZdrxD1ag/ApXRBOVDpC84FqwyltEPpRyC9mHo
    vHYoLLpvhXUc9QpjlzRKLpl9vVYOqW3EtMFeZFzzNejDZDEo5jNWQW5OasPywYjqFazQO4gb0PGV
    8yQ5e0Vx2PHbUKcB9DIrFmKkCbrbgxUIN5qvmMxVsRZtC7qMQ+qFSbPwdv8nkNBWfARr8bxja9o4
    m5rcSZ1XEVXTvpISdFLn9CNzIP1YXbd/5uj9BdvDDlnAzmp2uriJ/u3D+FzT4blGmwfveHXLDN9r
    wAvXeGItl3fye/S8+AtQSwECHgMUAAAACAAkiJ1ZwvbVsM4BAABzBQAABwAYAAAAAAABAAAApIEA
    AAAAbWFpbi5weVVUBQADhKpxZ3V4CwABBOgDAAAE6AMAAFBLBQYAAAAAAQABAE0AAAAPAgAAAAA=

