---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juniolima-serverless-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juniolima-serverless-redis
  template:
    metadata:
      labels:
        app: juniolima-serverless-redis
    spec:
      containers:
      - name: juniolima-serverless-redis
        image: junioveras/serverless-runtime:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - name: pyfile
          mountPath: "/opt/usermodule.py"
          subPath: pyfile
        env:
        - name: REDIS_HOST
          value: "192.168.121.48"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_INPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: config
              key: REDIS_INPUT_KEY
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
        - name: MONITORING_PERIOD
          valueFrom:
            configMapKeyRef:
              name: config
              key: MONITORING_PERIOD
        - name: PYFILE_OR_ZIP
          value: "zip"
        - name: ZIP_FILE_PATH
          value: "/opt/user_function.zip"
        - name: ZIP_ENTRY_FILE
          value: "main.py"
        - name: PYFILE_PATH
          value: "/opt/usermodule.py"
        - name: ENTRY_FUNCTION
          valueFrom:
            configMapKeyRef:
              name: config
              key: ENTRY_FUNCTION
        - name: ZIP_BASE64
          valueFrom:
            configMapKeyRef:
              name: config
              key: ZIP_BASE64
      volumes:
      - name: pyfile
        configMap:
          name: pyfile

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  REDIS_INPUT_KEY: "metrics"
  MONITORING_PERIOD: "5"
  ENTRY_FUNCTION: "handler"
  REDIS_OUTPUT_KEY: "juniolima-proj3-output"
  ZIP_BASE64: "UEsDBBQAAAAIAECXJFqUGF2OjwIAADoHAAAHABwAbWFpbi5weVVUCQAD5655Z+eueWd1eAsAAQToAwAABOgDAACNVE2PmzAQvfMrLCQk2IWUXHqItCv11ktP7aVCCDkwJO6Cjewh2zTKf6+NCZgk+8EB2Z55b+aNPVNL0RI8dozvCGs7IZF840dvXErwauNQUQRkLVxcLvuYmH8FDVLPq6Ame8qrBmTIeNfjhlSsxJiUgiP81Vux/QMlRiR5HiyZQhmTuhEU841H9Lc9IqhCAUfyRAaOzOeABRNFKXrNIlUBuE+T2dHPHaSE8vAppHEckax2wz66TM8ktXmZrwNZao9Cs74K+VLAToJSOlrowL8sdi5ZFJEHsk7TgQ8aBZ9gTlepN3i10Ap5LEpa7qGaBR6YxJ42hTUn1jzKGiHbvq619jcxo30JQoG0eRMyWOfiLTB3K+Zmb+oVLuU8XuUa6Sq6pB8X7irAVLay64seWcP+UWSCa1NmJb3AMSe1kEQvtEor1IjR+5VCKlG9MtyHvmEYoyR+ZDVfhA/GPVOoY/uECzRM41tfAT/MeTqH2QKV65RObEMymw0zDJLyHYQN8PAq/Sg6z/HpYVfcyjtZD9OehSZsqekjP/idBG0SVCT4vgl+bIKfq6D2bYF6+cu09dPU0Vq97MwiHC/frHVF2s7PY5c4siUe0o6Jm4bWALxvQWrnGw2fKUrG8hXtOuBVeBri+5tLpjHxD7TpzYnDeo4m1mnxumcNkKGM7wWK9JNdz0mNV0u36n1YlqxzWxt9h8n7WrJ0cjXRpokZtoz3ejw8raNlAh9XpxNdmEYL0LIzLt9WAn3xpuM7ryarfX2amJNEm07snHxNFZTD21R9Gy6jcJTHbLwD+2iHo6unf5vyxGK6++NbsSlLwF5ycprA/qUXx1GZ2FGpX8P9GRrfIt1Z6eDcETKjHh7uVGywnr3/UEsBAh4DFAAAAAgAQJckWpQYXY6PAgAAOgcAAAcAGAAAAAAAAQAAAKSBAAAAAG1haW4ucHlVVAUAA+eueWd1eAsAAQToAwAABOgDAABQSwUGAAAAAAEAAQBNAAAA0AIAAAAA"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pyfile
data:
  pyfile: "from typing import Any\nimport re\nfrom datetime import datetime, timedelta\n\ndef
    handler(input: dict, context: object) -> dict[str, float]:\n    bytes_sent = input[\"net_io_counters_eth0-bytes_sent\"]\n
    \   bytes_recv = input[\"net_io_counters_eth0-bytes_recv\"]\n    if bytes_sent
    + bytes_recv > 0:\n        percent_network_egress = (bytes_sent / (bytes_sent
    + bytes_recv)) * 100\n    else:\n        percent_network_egress = 0.0\n\n    memory_cached
    = input[\"virtual_memory-cached\"]\n    memory_buffers = input[\"virtual_memory-buffers\"]\n
    \   memory_total = input[\"virtual_memory-total\"]\n    if memory_total > 0:\n
    \       percent_memory_cache = ((memory_cached + memory_buffers) / memory_total)
    * 100\n    else:\n        percent_memory_cache = 0.0\n\n    cpu_utilization =
    [input[key] for key in input if key.startswith(\"cpu_percent-\")]\n    \n    if
    \"cpu_history\" not in context.env:\n        context.env[\"cpu_history\"] = {i:
    [] for i in range(len(cpu_utilization))}\n    \n    avg_cpu_utilization = {}\n
    \   date_format = \"%Y-%m-%d %H:%M:%S.%f\"\n    curTime = datetime.strptime(input[\"timestamp\"],
    date_format)\n\n    for i, utilization in enumerate(cpu_utilization):\n        context.env[\"cpu_history\"][i].append({\"time\":
    curTime, \"value\": utilization})\n        \n        while len(context.env[\"cpu_history\"][i])
    > 1:\n            if abs(context.env[\"cpu_history\"][i][-1][\"time\"] - context.env[\"cpu_history\"][i][0][\"time\"])
    > timedelta(minutes=1):\n                context.env[\"cpu_history\"][i].pop(0)\n
    \           else:\n                break\n\n        avg_cpu_utilization[f\"avg-util-cpu{i}-60sec\"]
    = sum(\n            entry[\"value\"] for entry in context.env[\"cpu_history\"][i]\n
    \       ) / len(context.env[\"cpu_history\"][i])\n\n    return {\n        \"percent-network-egress\":
    percent_network_egress,\n        \"percent-memory-cache\": percent_memory_cache,\n
    \       **avg_cpu_utilization\n    }\n"