apiVersion: v1
kind: Service
metadata:
  name: streamlit-dashboard-service
spec:
  type: NodePort
  selector:
    app: streamlit-dashboard
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
    nodePort: 32223
